repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
  - repo: local
    hooks:
      - id: flake8
        name: flake8
        entry: flake8 vela --indent-size=4 --ignore=E221,E302,E501,E701 --statistics -j4
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy -p vela --check-untyped-defs --explicit-package-bases --warn-unreachable
        language: system
        always_run: true
        pass_filenames: false